www/MotoGP/MotoGP/Models/ViewModels/ListTicketsViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MotoGP.Models.ViewModels
{
    public class ListTicketsViewModel
    {
        public List<Ticket> Tickets;
        public SelectList Races { get; set; }

        public int raceID { get; set; }
        public string Country { get; set; }

    }
}

www/MotoGP/MotoGP/Controllers/InfoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MotoGP.Data;
using MotoGP.Models;
using MotoGP.Models.ViewModels;

namespace MotoGP.Controllers
{
    public class InfoController : Controller
    {
        private readonly GPContext _context;

        public InfoController(GPContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ListRaces()
        {
            ViewData["BannerNr"] = 0;
            ViewData["Title"] = "Races";
            var races = _context.Races.OrderBy(r => r.Date);
            return View(races);

        }

        public IActionResult ShowRace(int id)
        {
            var check = id;
            ViewData["BannerNr"] = 0;
            //Race race = _context.Races.Where(r => r.RaceID == RaceID).SingleOrDefault();
            Race race = _context.Races
                            .SingleOrDefault(r => r.RaceID == id);
            ViewData["Title"] = "Race - " + race.Name;
            return View(race);
        }

        public IActionResult SelectRace(int raceID = 0)
        {

            var selectRaceVM = new SelectRaceViewModel();
            if (raceID != 0)
            {
                selectRaceVM.raceID = raceID;
                Race race = _context.Races.Where(r => r.RaceID == raceID).SingleOrDefault();
                selectRaceVM.raceID = race.RaceID;
                selectRaceVM.Name = race.Name;
                selectRaceVM.Description = race.Description;
                selectRaceVM.Country = race.Country;
                selectRaceVM.Length = race.Length;
                selectRaceVM.Date = race.Date;
            }
            ViewData["Title"] = "Races";
            selectRaceVM.Races = new SelectList(_context.Races.OrderBy(r => r.Name), "RaceID", "Name");
            selectRaceVM.raceID = raceID;
            return View(selectRaceVM);
        }

        public IActionResult ListRiders()
        {
            ViewData["BannerNr"] = 1;
            ViewData["Title"] = "Riders";
            var riders = _context.Riders.OrderBy(r => r.Number);
            return View(riders);
        }


        public IActionResult BuildMap()
        {
            Race race1 = new Race { RaceID = 1, X = 517, Y = 19, Name = "Assen" };
            Race race2 = new Race { RaceID = 2, X = 859, Y = 249, Name = "Losail Circuit" };
            Race race3 = new Race { RaceID = 3, X = 194, Y = 428, Name = "Autódromo Termas de Río Hondo" };
            var raceList = new List<Race> { race1, race2, race3 };

            ViewData["RaceList"] = raceList;
            ViewData["Title"] = "Races on map";
            return View();

        }
    }
}

www/MotoGP/MotoGP/Controllers/ShopController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MotoGP.Data;
using MotoGP.Models;
using MotoGP.Models.ViewModels;

namespace MotoGP.Controllers
{
    public class ShopController : Controller
    {
        private readonly GPContext _context;

        public ShopController(GPContext context)
        {
            _context = context;
        }

        public IActionResult ListTickets(int raceID)
        {
            ViewData["BannerNr"] = 3;
            var listTicketsVM = new ListTicketsViewModel();
            listTicketsVM.Races = new SelectList(_context.Races.OrderBy(r => r.Name), "RaceID", "Name");
            if (raceID != 0)
            {
                listTicketsVM.Tickets = _context.Tickets.OrderByDescending(d => d.OrderDate).Where(t => t.RaceID == raceID).ToList();
                return View(listTicketsVM);
            }


            listTicketsVM.Tickets = _context.Tickets.OrderByDescending(d => d.OrderDate).ToList();

            return View(listTicketsVM);
        }

        public IActionResult ConfirmOrder(int TicketID)
        {
            ViewData["BannerNr"] = 3;
            ViewData["Title"] = "Confirmation";
            Ticket ticket = _context.Tickets.Where(t => t.TicketID == TicketID).Include(t => t.Race).SingleOrDefault();
            return View(ticket);
        }

        //GET: Tickets/Create
        public IActionResult OrderTicket()
        {
            ViewData["BannerNr"] = 3;
            ViewData["Title"] = "Order Tickets";
            ViewData["Countries"] = new SelectList(_context.Countries.OrderBy(c => c.Name), "CountryID", "Name");
            ViewData["Races"] = _context.Races.OrderBy(c => c.Name);
            return View();
        }




        //POST: Tickets
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult OrderTicket([Bind("TicketID,Name,Email,Address,Number,CountryID,RaceID")] Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                ticket.Paid = false;
                _context.Add(ticket);
                _context.SaveChanges();
                return RedirectToAction("ConfirmOrder", new { ticketID = ticket.TicketID });
            }

            return View(ticket);

        }

        //Editicket

        public IActionResult EditTicket(int id)
        {
            ViewData["BannerNr"] = 3;
            ViewData["Title"] = "Edit Tickets";

            Ticket ticket = _context.Tickets.Include(t => t.Race).Include(t => t.Country).SingleOrDefault(t => t.TicketID == id);
            return View(ticket);
        }

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public IActionResult EditTicket([Bind("TicketID,Paid,Email,Address,Name,CountryID,RaceID")] Ticket ticket)
        //{

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(ticket);
        //            _context.SaveChanges();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            throw;
        //        }
        //        //ticket.Paid = false;
        //        //_context.Add(ticket);
        //        //_context.SaveChanges();
        //        return RedirectToAction("ListTickets");
        //    }
        //    var listTicketsVM = new ListTicketsViewModel();
        //    listTicketsVM.Tickets = _context.Tickets.OrderByDescending(d => d.OrderDate).ToList();
        //    listTicketsVM.Races = new SelectList(_context.Races.OrderBy(r => r.Name), "RaceID", "Name");
        //    return View(ticket);

        //}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditTicket([Bind("TicketID,Paid")] Ticket ticket)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Attach(ticket);
                    _context.Entry(ticket).Property(t => t.Paid).IsModified = true;
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }
                //ticket.Paid = false;
                //_context.Add(ticket);
                //_context.SaveChanges();
                return RedirectToAction("ListTickets");
            }
            var listTicketsVM = new ListTicketsViewModel();
            listTicketsVM.Tickets = _context.Tickets.OrderByDescending(d => d.OrderDate).ToList();
            listTicketsVM.Races = new SelectList(_context.Races.OrderBy(r => r.Name), "RaceID", "Name");
            return View(ticket);

        }


    }
}

www/MotoGP/MotoGP/Views/Shop/ConfirmOrder.cshtml
@ViewData["_Layout"]

@model MotoGP.Models.Ticket

@{
    DateTime now = DateTime.Now;
    string strDate = now.ToString("dd/M/yyyy");

}
<p>Thank you <b>@Model.Name</b> for ordering tickets in <b> @Model.Address</b>  on <b>@Model.OrderDate</b> for the race. Your booking is registered on <b>@strDate</b> . We will send the <b>@Model.Number</b>  tickets as soon as possible.</p>
<a asp-controller="Home" asp-action="Menu">Back</a>

www/MotoGP/MotoGP/Views/Shop/EditTicket.cshtml
@model MotoGP.Models.Ticket


<form asp-action="EditTicket">
    <input type="hidden" asp-for="TicketID"/>
    
    @*<input type="hidden" asp-for="Name"/>*@
    <p>asp-for="Name">@Html.DisplayNameFor(model=>model.Name)  @Html.DisplayFor(model => model.Name)</p>

    <p>@Html.DisplayNameFor(model =>model.Email)  @Html.DisplayFor(model => model.Email)</p>
@*  <input type="hidden" asp-for="Email"/>
*@    @*<p asp-for="Address">@Html.DisplayNameFor(model =>model.Address)  @Html.DisplayFor(model => model.Address)</p>*@
   @* <input type="hidden" asp-for="Address"/>*@

    <p>@Html.DisplayNameFor(model =>model.Country)  @Html.DisplayFor(model => model.Country.Name)</p>
    @*<input type="hidden" asp-for="CountryID"/>*@

    <p>@Html.DisplayNameFor(model =>model.Race)  @Html.DisplayFor(model => model.Race.Name)</p>
    @*<input type="hidden" asp-for="RaceID"/>*@

    <p>@Html.DisplayNameFor(model =>model.Number)  @Html.DisplayFor(model => model.Number)</p>
    @*<input type="hidden" asp-for="Number"/>*@
    
    <input type="checkbox" asp-for="Paid" value="True"/>
    <label asp-for="Paid">@Html.DisplayNameFor(model => model.Paid)</label>,
    <br />

    <input type="submit" value="Register"/><br />
</form>

www/MotoGP/MotoGP/Views/Shop/ListTickets.cshtml
@model MotoGP.Models.ViewModels.ListTicketsViewModel



<form asp-controller="Shop" asp-action="ListTickets" method="get">
    <select asp-for="raceID" asp-items="Model.Races">
        <option value="0">--Select a race--</option>
    </select>
    <input type="submit" value="Get race" />
</form>

@{
    if(Model.Tickets.Count != 0)
    {
        
      <table>
    <tr>
        <td>@(Html.DisplayNameFor(model => model.Tickets[0].OrderDate))</td>
        <td>@(Html.DisplayNameFor(model => model.Tickets[0].Name))</td>
        <td>@(Html.DisplayNameFor(model => model.Tickets[0].Email))</td>
        <td>@(Html.DisplayNameFor(model => model.Tickets[0].Address))</td>
        <td>@(Html.DisplayNameFor(model => model.Tickets[0].Country))</td>
        <td>@(Html.DisplayNameFor(model => model.Tickets[0].Race))</td>
        <td>@(Html.DisplayNameFor(model => model.Tickets[0].Number))</td>
        <td></td>
       
    </tr>
    @foreach (var item in Model.Tickets)
    {
        <tr>
            
            <td>@(Html.DisplayFor(modelItem => item.OrderDate))</td>
            <td>@(Html.DisplayFor(modelItem => item.Name))</td>
            <td>@(Html.DisplayFor(modelItem => item.Email))</td>
            <td>@(Html.DisplayFor(modelItem => item.Address))</td>
            <td>@(Html.DisplayFor(modelItem => item.Race.Country))</td>
            <td>@(Html.DisplayFor(modelItem => item.Race.Name))</td>
            <td>@(Html.DisplayFor(modelItem => item.Number))</td>
            @{
                if(item.Paid){
                            <td>Paid</td>
                        }
                        else
                        {
                            <td><a asp-controller="Shop" asp-action="EditTicket" asp-route-id="@item.TicketID">Pay</a></td>
                        }
                        
            }
        </tr>
    }

        </table>
    }
    else
    {
        <p>No tickets ordered for this race</p>
    }
}

<a asp-controller="Info" asp-action="OrderTicket">Back</a>

www/MotoGP/MotoGP/Views/Shop/OrderTicket.cshtml
@{
    Layout = "_Layout";
    var countries = (IEnumerable<SelectListItem>)ViewData["Countries"]!;
    var races = (IEnumerable<Race>)ViewData["Races"]!;
}

@model MotoGP.Models.Ticket

<p>Please fill out the following</p>

<form asp-action="OrderTicket">
    <label asp-for="Name">@Html.DisplayNameFor(model=>model.Name)</label>
    <input asp-for="Name"/><br/>

    <label asp-for="Email">@Html.DisplayNameFor(model =>model.Email)</label>
    <input asp-for="Email"/><br />

    <label asp-for="Address">@Html.DisplayNameFor(model =>model.Address)</label>
    <input asp-for="Address"/><br />

    <label asp-for="CountryID">@Html.DisplayNameFor(model =>model.Country)</label>
    <select asp-for="CountryID" asp-items="countries"></select><br />

    <label asp-for="Number">@Html.DisplayNameFor(model =>model.Number)</label>
    <input type="radio" asp-for="Number" value="1"/>
    <label asp-for="Number">1</label>
    <input type="radio" asp-for="Number" value="2"/>
     <label asp-for="Number">2</label>
     <input type="radio" asp-for="Number" value="3"/>
     <label asp-for="Number">3</label>
     <input type="radio" asp-for="Number" value="4"/>
     <label asp-for="Number">4</label>
     <input type="radio" asp-for="Number" value="5"/>
     <label asp-for="Number">5</label>
     <input type="radio" asp-for="Number" value="6"/>
     <label asp-for="Number">6</label><br />

     <label>Race</label><br />
     <div>@{
        foreach(var race in races)
        {
            <input type="radio" asp-for="RaceID" value="@race.RaceID"/>
            <label asp-for="@race.Name">@race.Name</label><br />
        }
    }</div>
    
     
    
    
    
    
    
    
    
    <br />

    <input type="submit" value="Order"/><br />
</form>

<a asp-controller="Home" asp-action="Menu">Back</a>